namespace Chip
{
    public enum Tags
    {
        LevelWall,
        Solid,
        Arcade,
        Box,
        Computer,
        SavePoint,
        FakeWall,
        Player,
        PlayerBullet,
        Enemy,
        Item,
        Door,
        Water,
        Piece,
        Sceneries,
        Rocket,
        RocketPanel,
        HiddenPlace,
        Acid,
        Bomb,
        Rope,
        HUD,
        Trigger,
        Reward
    }
}